### ISSUE TITLE
Can you please revive this script for the latest version? I didnt even know how much I needed it 

### ISSUE THREAD

**Issue by sakanatha** [thepante/SAL-Firefox#3]

**Comment by thepante** [comment]
Hey thank you for the comment haha.
I will try to update it on this weekend, I'll let you know when it is ready!

**Comment by sakanatha** [comment]
Actually, it looks like I lied to you. I just misunderstood the purpose of this script, I thought that it somehow saves content from the sidebar panels, not just hides it (for example so you can switch to history, then back to addon without reloading and then back to history without reloading, losing focus). So because of this and that the existing hotkeys and addon buttons didnt work i thought that its broken, but it actually looks fine, i guess, on 107  hotkey works fine, sidebar button works fine, hiding works fine. Only the float mode is not resizable at all, although in your video you somehow managed to resize it even vertically. Or I just didnt understand how to do it . So, sorry I guess. Although compatibility with other scriptloaders like mrotherguy's or xiaoxiaoflood's would be nice
